# Generated by Django 5.2.1 on 2025-05-20 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='garbage_fee',
        ),
        migrations.AddField(
            model_name='apartment',
            name='trash_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='gas_fee',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='water_fee',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Data terminu płatności')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('rent', 'Czynsz'), ('garbage', 'Śmieci'), ('water', 'Woda'), ('gas', 'Gaz')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('paid', 'Opłacone')], default='pending', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenant')),
            ],
        ),
    ]
